artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/206131405281213884
creation_time: 1732215365124
experiment_id: '206131405281213884'
last_update_time: 1732215365124
lifecycle_stage: active
name: /Shared/Ultralytics
