artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/955403493635297905
creation_time: 1732230001554
experiment_id: '955403493635297905'
last_update_time: 1732230001554
lifecycle_stage: active
name: /Shared/Ultralytics
