artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/604821644590381973
creation_time: 1732214306682
experiment_id: '604821644590381973'
last_update_time: 1732214306682
lifecycle_stage: active
name: /Shared/Ultralytics
