artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/908708828658248507
creation_time: 1732228039316
experiment_id: '908708828658248507'
last_update_time: 1732228039316
lifecycle_stage: active
name: /Shared/Ultralytics
