artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/303618061126596037
creation_time: 1732214299190
experiment_id: '303618061126596037'
last_update_time: 1732214299190
lifecycle_stage: active
name: training
