artifact_location: file:///home/pedro/Documents/mlops/24-2-mlops-project-car_object_detection/src/../models/runs/mlflow/0
creation_time: 1732214299183
experiment_id: '0'
last_update_time: 1732214299183
lifecycle_stage: active
name: Default
